"""Add firewall table

Revision ID: 3b2e39593835
Revises: 
Create Date: 2024-11-03 20:15:03.950102

"""
from typing import Sequence, Union

from alembic import op
from app.db import custom_types
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b2e39593835'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firewall',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('ip_address', custom_types.IPv4Address(length=15), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address', 'port')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('firewall')
    # ### end Alembic commands ###
