"""Add filtering policy table

Revision ID: b15c7cd45dcb
Revises: 3b2e39593835
Create Date: 2024-11-04 14:45:52.579267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b15c7cd45dcb'
down_revision: Union[str, None] = '3b2e39593835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filtering_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firewall_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('next_policy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['firewall_id'], ['firewall.id'], ),
    sa.ForeignKeyConstraint(['next_policy_id'], ['filtering_policy.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firewall_id', 'name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filtering_policy')
    # ### end Alembic commands ###
